//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR07_06
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        public int PriductID { get; set; }
        public int PartnerID { get; set; }
        public Nullable<double> CountPhoduct { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
    }
}
